### ISSUE TITLE
Accessing http://archive-new.nrao.edu/vlass/HiPS/VLASS1.1/Quicklook

### ISSUE THREAD

**Issue by richardgmcmahon** [hipspy/hips#126]
I would like to access and make a image from:

http://archive-new.nrao.edu/vlass/HiPS/VLASS1.1/Quicklook

The docs at:
https://hips.readthedocs.io/en/latest/getting_started.html#make-a-sky-image

Say
Specify the HiPS survey you want. You just need to provide a valid HiPS survey ID.

A good address that lists available HiPS data is http://aladin.u-strasbg.fr/hips/list

But https://hips.readthedocs.io/en/latest/getting_started.html#make-a-sky-image

is not listed.

How do I proceed?

**Comment by adl1995** [comment]
The default URL that `hips` searches from is: http://alasky.unistra.fr/MocServer/query?hips_service_url=*&dataproduct_type=!catalog&dataproduct_type=!cube&get=record%27

Since the survey you're trying to query is not listed there, you can manually create a `HipsSurveyProperties` object and pass it to the `make_sky_image` function.

To create the object you just need to provide a URL to HiPS properties:
```python
hips_survey = HipsSurveyProperties.fetch("http://archive-new.nrao.edu/vlass/HiPS/VLASS1.1/Quicklook/properties")
```

The remaining workflow should remain the same.

**Comment by richardgmcmahon** [comment]
Thanks, that worked with:

from hips import HipsSurveyProperties

**Comment by adl1995** [comment]
Glad it worked!
