### ISSUE TITLE
Introduce method for creating children tiles

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips#83]
As discussed during telecon today with @cdeil (also mentioned in the [precise algorithm](https://hips.readthedocs.io/en/latest/drawing_algo.html#tile-distortion-issue)), I will open a PR adding a method named: `make_child_tiles`(?) which will take as parameter the father tile. It will then split this into four children tiles by slicing the father tile into four quarters. It will use something like: tile[0, width / 4] and then call [HipsTile.from_numpy](http://hips.readthedocs.io/en/latest/api/hips.HipsTile.html?highlight=from_numpy#hips.HipsTile.from_numpy) class method. The new tiles will be labeled according to the scheme mentioned in the [HiPS paper](http://www.ivoa.net/documents/HiPS/20160623/WD-HiPS-1.0-20160623.pdf), page 31, titled "Children of the tile".

**Comment by cdeil** [comment]
I'm never sure with naming at first and then find that only over time as one starts to call the functionality good names and locations for code are found. In this case, I think I would start by putting it as a property on `HipsTile` called `children` which returns the list of 4 child tiles.

There should be a good docstring and a parameterised test using these tiles we already have with the different formats: https://github.com/hipspy/hips/blob/master/hips/tiles/tests/test_tile.py#L54

Otherwise, yes, your description sounds good to me ... go ahead!

**Comment by adl1995** [comment]
Done in #85. Closing this issue now.
